//******************************************************************************
//
// Project : Alarm Clock V3
// File    : src/libs/tzdata.h
// Author  : Benoit Frigon <www.bfrigon.com>
//
// -----------------------------------------------------------------------------
//
//                           [ Important! ]
//
// This file is auto-generated by the script gen_tzdata.sh in /tools/tzdata. 
// This scripts download the timezone database from IANA and generates the time 
// zone table bellow
//
// DO NOT EDIT ANYTHING IN THIS FILE AS IT WILL BE OVERWRITTEN
//
// -----------------------------------------------------------------------------
//
// This work is licensed under the Creative Commons Attribution-ShareAlike 4.0
// International License. To view a copy of this license, visit
//
// http://creativecommons.org/licenses/by-sa/4.0/
//
// or send a letter to Creative Commons,
// PO Box 1866, Mountain View, CA 94042, USA.
//
//******************************************************************************
#ifndef TZDATA_H
#define TZDATA_H

#include <Arduino.h>
#include <avr/pgmspace.h>
#include "time.h"

#define MAX_TIMEZONE_ID     426
#define TZ_DB_VERSION       "2020f"


const char TZ_UTC[] PROGMEM = { "UTC" };
const char TZ_ACDT[] PROGMEM = { "ACDT" };
const char TZ_ACST[] PROGMEM = { "ACST" };
const char TZ_ACT[] PROGMEM = { "ACT" };
const char TZ_ADT[] PROGMEM = { "ADT" };
const char TZ_AEDT[] PROGMEM = { "AEDT" };
const char TZ_AEST[] PROGMEM = { "AEST" };
const char TZ_AET[] PROGMEM = { "AET" };
const char TZ_AKDT[] PROGMEM = { "AKDT" };
const char TZ_AKST[] PROGMEM = { "AKST" };
const char TZ_AST[] PROGMEM = { "AST" };
const char TZ_AT[] PROGMEM = { "AT" };
const char TZ_AWST[] PROGMEM = { "AWST" };
const char TZ_AWT[] PROGMEM = { "AWT" };
const char TZ_CAT[] PROGMEM = { "CAT" };
const char TZ_CDT[] PROGMEM = { "CDT" };
const char TZ_CEST[] PROGMEM = { "CEST" };
const char TZ_CET[] PROGMEM = { "CET" };
const char TZ_CHST[] PROGMEM = { "ChST" };
const char TZ_CST[] PROGMEM = { "CST" };
const char TZ_CT[] PROGMEM = { "CT" };
const char TZ_EAT[] PROGMEM = { "EAT" };
const char TZ_EDT[] PROGMEM = { "EDT" };
const char TZ_EEST[] PROGMEM = { "EEST" };
const char TZ_EET[] PROGMEM = { "EET" };
const char TZ_EST[] PROGMEM = { "EST" };
const char TZ_GMT[] PROGMEM = { "GMT" };
const char TZ_GMT_BST[] PROGMEM = { "GMT/BST" };
const char TZ_HDT[] PROGMEM = { "HDT" };
const char TZ_HKT[] PROGMEM = { "HKT" };
const char TZ_HST[] PROGMEM = { "HST" };
const char TZ_IDT[] PROGMEM = { "IDT" };
const char TZ_IST[] PROGMEM = { "IST" };
const char TZ_IST_GMT[] PROGMEM = { "IST/GMT" };
const char TZ_JST[] PROGMEM = { "JST" };
const char TZ_JT[] PROGMEM = { "JT" };
const char TZ_KST[] PROGMEM = { "KST" };
const char TZ_KT[] PROGMEM = { "KT" };
const char TZ_M01[] PROGMEM = { "-01" };
const char TZ_M01_P00[] PROGMEM = { "-01/+00" };
const char TZ_M02[] PROGMEM = { "-02" };
const char TZ_M03[] PROGMEM = { "-03" };
const char TZ_M03_M02[] PROGMEM = { "-03/-02" };
const char TZ_M04[] PROGMEM = { "-04" };
const char TZ_M04_M03[] PROGMEM = { "-04/-03" };
const char TZ_M05[] PROGMEM = { "-05" };
const char TZ_M05_M04[] PROGMEM = { "-05/-04" };
const char TZ_M06_M05[] PROGMEM = { "-06/-05" };
const char TZ_M08[] PROGMEM = { "-08" };
const char TZ_M0930[] PROGMEM = { "-0930" };
const char TZ_M09[] PROGMEM = { "-09" };
const char TZ_M10[] PROGMEM = { "-10" };
const char TZ_M10_M0930[] PROGMEM = { "-10/-0930" };
const char TZ_M11[] PROGMEM = { "-11" };
const char TZ_MDT[] PROGMEM = { "MDT" };
const char TZ_MSK[] PROGMEM = { "MSK" };
const char TZ_MST[] PROGMEM = { "MST" };
const char TZ_NDT[] PROGMEM = { "NDT" };
const char TZ_NST[] PROGMEM = { "NST" };
const char TZ_NZDT[] PROGMEM = { "NZDT" };
const char TZ_NZST[] PROGMEM = { "NZST" };
const char TZ_P00[] PROGMEM = { "+00" };
const char TZ_P01_P00[] PROGMEM = { "+01/+00" };
const char TZ_P02[] PROGMEM = { "+02" };
const char TZ_P0330_P0430[] PROGMEM = { "+0330/+0430" };
const char TZ_P03[] PROGMEM = { "+03" };
const char TZ_P03_P04[] PROGMEM = { "+03/+04" };
const char TZ_P0430[] PROGMEM = { "+0430" };
const char TZ_P04[] PROGMEM = { "+04" };
const char TZ_P04_P05[] PROGMEM = { "+04/+05" };
const char TZ_P0530[] PROGMEM = { "+0530" };
const char TZ_P0545[] PROGMEM = { "+0545" };
const char TZ_P05[] PROGMEM = { "+05" };
const char TZ_P0630[] PROGMEM = { "+0630" };
const char TZ_P06[] PROGMEM = { "+06" };
const char TZ_P06_P07[] PROGMEM = { "+06/+07" };
const char TZ_P07[] PROGMEM = { "+07" };
const char TZ_P07_P08[] PROGMEM = { "+07/+08" };
const char TZ_P0845_P0945[] PROGMEM = { "+0845/+0945" };
const char TZ_P08[] PROGMEM = { "+08" };
const char TZ_P08_P09[] PROGMEM = { "+08/+09" };
const char TZ_P09[] PROGMEM = { "+09" };
const char TZ_P1030_P11[] PROGMEM = { "+1030/+11" };
const char TZ_P10[] PROGMEM = { "+10" };
const char TZ_P11[] PROGMEM = { "+11" };
const char TZ_P11_P12[] PROGMEM = { "+11/+12" };
const char TZ_P1245_P1345[] PROGMEM = { "+1245/+1345" };
const char TZ_P12[] PROGMEM = { "+12" };
const char TZ_P12_P13[] PROGMEM = { "+12/+13" };
const char TZ_P13[] PROGMEM = { "+13" };
const char TZ_P13_P14[] PROGMEM = { "+13/+14" };
const char TZ_P14[] PROGMEM = { "+14" };
const char TZ_PDT[] PROGMEM = { "PDT" };
const char TZ_PKT[] PROGMEM = { "PKT" };
const char TZ_PST[] PROGMEM = { "PST" };
const char TZ_PT[] PROGMEM = { "PT" };
const char TZ_SAST[] PROGMEM = { "SAST" };
const char TZ_SST[] PROGMEM = { "SST" };
const char TZ_WAT[] PROGMEM = { "WAT" };
const char TZ_WEST[] PROGMEM = { "WEST" };
const char TZ_WET[] PROGMEM = { "WET" };
const char TZ_WIB[] PROGMEM = { "WIB" };
const char TZ_WITA[] PROGMEM = { "WITA" };
const char TZ_WIT[] PROGMEM = { "WIT" };


const char TZ_ETC_UTC[] PROGMEM = { "Etc/UTC" };
const char TZ_AFRICA_ABIDJAN[] PROGMEM = { "Africa/Abidjan" };
const char TZ_AFRICA_ACCRA[] PROGMEM = { "Africa/Accra" };
const char TZ_AFRICA_ADDIS_ABABA[] PROGMEM = { "Africa/Addis_Ababa" };
const char TZ_AFRICA_ALGIERS[] PROGMEM = { "Africa/Algiers" };
const char TZ_AFRICA_ASMARA[] PROGMEM = { "Africa/Asmara" };
const char TZ_AFRICA_BAMAKO[] PROGMEM = { "Africa/Bamako" };
const char TZ_AFRICA_BANGUI[] PROGMEM = { "Africa/Bangui" };
const char TZ_AFRICA_BANJUL[] PROGMEM = { "Africa/Banjul" };
const char TZ_AFRICA_BISSAU[] PROGMEM = { "Africa/Bissau" };
const char TZ_AFRICA_BLANTYRE[] PROGMEM = { "Africa/Blantyre" };
const char TZ_AFRICA_BRAZZAVILLE[] PROGMEM = { "Africa/Brazzaville" };
const char TZ_AFRICA_BUJUMBURA[] PROGMEM = { "Africa/Bujumbura" };
const char TZ_AFRICA_CAIRO[] PROGMEM = { "Africa/Cairo" };
const char TZ_AFRICA_CASABLANCA[] PROGMEM = { "Africa/Casablanca" };
const char TZ_AFRICA_CEUTA[] PROGMEM = { "Africa/Ceuta" };
const char TZ_AFRICA_CONAKRY[] PROGMEM = { "Africa/Conakry" };
const char TZ_AFRICA_DAKAR[] PROGMEM = { "Africa/Dakar" };
const char TZ_AFRICA_DAR_ES_SALAAM[] PROGMEM = { "Africa/Dar_es_Salaam" };
const char TZ_AFRICA_DJIBOUTI[] PROGMEM = { "Africa/Djibouti" };
const char TZ_AFRICA_DOUALA[] PROGMEM = { "Africa/Douala" };
const char TZ_AFRICA_EL_AAIUN[] PROGMEM = { "Africa/El_Aaiun" };
const char TZ_AFRICA_FREETOWN[] PROGMEM = { "Africa/Freetown" };
const char TZ_AFRICA_GABORONE[] PROGMEM = { "Africa/Gaborone" };
const char TZ_AFRICA_HARARE[] PROGMEM = { "Africa/Harare" };
const char TZ_AFRICA_JOHANNESBURG[] PROGMEM = { "Africa/Johannesburg" };
const char TZ_AFRICA_JUBA[] PROGMEM = { "Africa/Juba" };
const char TZ_AFRICA_KAMPALA[] PROGMEM = { "Africa/Kampala" };
const char TZ_AFRICA_KHARTOUM[] PROGMEM = { "Africa/Khartoum" };
const char TZ_AFRICA_KIGALI[] PROGMEM = { "Africa/Kigali" };
const char TZ_AFRICA_KINSHASA[] PROGMEM = { "Africa/Kinshasa" };
const char TZ_AFRICA_LAGOS[] PROGMEM = { "Africa/Lagos" };
const char TZ_AFRICA_LIBREVILLE[] PROGMEM = { "Africa/Libreville" };
const char TZ_AFRICA_LOME[] PROGMEM = { "Africa/Lome" };
const char TZ_AFRICA_LUANDA[] PROGMEM = { "Africa/Luanda" };
const char TZ_AFRICA_LUBUMBASHI[] PROGMEM = { "Africa/Lubumbashi" };
const char TZ_AFRICA_LUSAKA[] PROGMEM = { "Africa/Lusaka" };
const char TZ_AFRICA_MALABO[] PROGMEM = { "Africa/Malabo" };
const char TZ_AFRICA_MAPUTO[] PROGMEM = { "Africa/Maputo" };
const char TZ_AFRICA_MASERU[] PROGMEM = { "Africa/Maseru" };
const char TZ_AFRICA_MBABANE[] PROGMEM = { "Africa/Mbabane" };
const char TZ_AFRICA_MOGADISHU[] PROGMEM = { "Africa/Mogadishu" };
const char TZ_AFRICA_MONROVIA[] PROGMEM = { "Africa/Monrovia" };
const char TZ_AFRICA_NAIROBI[] PROGMEM = { "Africa/Nairobi" };
const char TZ_AFRICA_NDJAMENA[] PROGMEM = { "Africa/Ndjamena" };
const char TZ_AFRICA_NIAMEY[] PROGMEM = { "Africa/Niamey" };
const char TZ_AFRICA_NOUAKCHOTT[] PROGMEM = { "Africa/Nouakchott" };
const char TZ_AFRICA_OUAGADOUGOU[] PROGMEM = { "Africa/Ouagadougou" };
const char TZ_AFRICA_PORTO_NOVO[] PROGMEM = { "Africa/Porto-Novo" };
const char TZ_AFRICA_SAO_TOME[] PROGMEM = { "Africa/Sao_Tome" };
const char TZ_AFRICA_TRIPOLI[] PROGMEM = { "Africa/Tripoli" };
const char TZ_AFRICA_TUNIS[] PROGMEM = { "Africa/Tunis" };
const char TZ_AFRICA_WINDHOEK[] PROGMEM = { "Africa/Windhoek" };
const char TZ_AMERICA_ADAK[] PROGMEM = { "America/Adak" };
const char TZ_AMERICA_ANCHORAGE[] PROGMEM = { "America/Anchorage" };
const char TZ_AMERICA_ANGUILLA[] PROGMEM = { "America/Anguilla" };
const char TZ_AMERICA_ANTIGUA[] PROGMEM = { "America/Antigua" };
const char TZ_AMERICA_ARAGUAINA[] PROGMEM = { "America/Araguaina" };
const char TZ_AMERICA_ARGENTINA_BUENOS_AIRES[] PROGMEM = { "America/Argentina/Buenos_Aires" };
const char TZ_AMERICA_ARGENTINA_CATAMARCA[] PROGMEM = { "America/Argentina/Catamarca" };
const char TZ_AMERICA_ARGENTINA_CORDOBA[] PROGMEM = { "America/Argentina/Cordoba" };
const char TZ_AMERICA_ARGENTINA_JUJUY[] PROGMEM = { "America/Argentina/Jujuy" };
const char TZ_AMERICA_ARGENTINA_LA_RIOJA[] PROGMEM = { "America/Argentina/La_Rioja" };
const char TZ_AMERICA_ARGENTINA_MENDOZA[] PROGMEM = { "America/Argentina/Mendoza" };
const char TZ_AMERICA_ARGENTINA_RIO_GALLEGOS[] PROGMEM = { "America/Argentina/Rio_Gallegos" };
const char TZ_AMERICA_ARGENTINA_SALTA[] PROGMEM = { "America/Argentina/Salta" };
const char TZ_AMERICA_ARGENTINA_SAN_JUAN[] PROGMEM = { "America/Argentina/San_Juan" };
const char TZ_AMERICA_ARGENTINA_SAN_LUIS[] PROGMEM = { "America/Argentina/San_Luis" };
const char TZ_AMERICA_ARGENTINA_TUCUMAN[] PROGMEM = { "America/Argentina/Tucuman" };
const char TZ_AMERICA_ARGENTINA_USHUAIA[] PROGMEM = { "America/Argentina/Ushuaia" };
const char TZ_AMERICA_ARUBA[] PROGMEM = { "America/Aruba" };
const char TZ_AMERICA_ASUNCION[] PROGMEM = { "America/Asuncion" };
const char TZ_AMERICA_ATIKOKAN[] PROGMEM = { "America/Atikokan" };
const char TZ_AMERICA_BAHIA[] PROGMEM = { "America/Bahia" };
const char TZ_AMERICA_BAHIA_BANDERAS[] PROGMEM = { "America/Bahia_Banderas" };
const char TZ_AMERICA_BARBADOS[] PROGMEM = { "America/Barbados" };
const char TZ_AMERICA_BELEM[] PROGMEM = { "America/Belem" };
const char TZ_AMERICA_BELIZE[] PROGMEM = { "America/Belize" };
const char TZ_AMERICA_BLANC_SABLON[] PROGMEM = { "America/Blanc-Sablon" };
const char TZ_AMERICA_BOA_VISTA[] PROGMEM = { "America/Boa_Vista" };
const char TZ_AMERICA_BOGOTA[] PROGMEM = { "America/Bogota" };
const char TZ_AMERICA_BOISE[] PROGMEM = { "America/Boise" };
const char TZ_AMERICA_CAMBRIDGE_BAY[] PROGMEM = { "America/Cambridge_Bay" };
const char TZ_AMERICA_CAMPO_GRANDE[] PROGMEM = { "America/Campo_Grande" };
const char TZ_AMERICA_CANCUN[] PROGMEM = { "America/Cancun" };
const char TZ_AMERICA_CARACAS[] PROGMEM = { "America/Caracas" };
const char TZ_AMERICA_CAYENNE[] PROGMEM = { "America/Cayenne" };
const char TZ_AMERICA_CAYMAN[] PROGMEM = { "America/Cayman" };
const char TZ_AMERICA_CHICAGO[] PROGMEM = { "America/Chicago" };
const char TZ_AMERICA_CHIHUAHUA[] PROGMEM = { "America/Chihuahua" };
const char TZ_AMERICA_COSTA_RICA[] PROGMEM = { "America/Costa_Rica" };
const char TZ_AMERICA_CRESTON[] PROGMEM = { "America/Creston" };
const char TZ_AMERICA_CUIABA[] PROGMEM = { "America/Cuiaba" };
const char TZ_AMERICA_CURACAO[] PROGMEM = { "America/Curacao" };
const char TZ_AMERICA_DANMARKSHAVN[] PROGMEM = { "America/Danmarkshavn" };
const char TZ_AMERICA_DAWSON[] PROGMEM = { "America/Dawson" };
const char TZ_AMERICA_DAWSON_CREEK[] PROGMEM = { "America/Dawson_Creek" };
const char TZ_AMERICA_DENVER[] PROGMEM = { "America/Denver" };
const char TZ_AMERICA_DETROIT[] PROGMEM = { "America/Detroit" };
const char TZ_AMERICA_DOMINICA[] PROGMEM = { "America/Dominica" };
const char TZ_AMERICA_EDMONTON[] PROGMEM = { "America/Edmonton" };
const char TZ_AMERICA_EIRUNEPE[] PROGMEM = { "America/Eirunepe" };
const char TZ_AMERICA_EL_SALVADOR[] PROGMEM = { "America/El_Salvador" };
const char TZ_AMERICA_FORTALEZA[] PROGMEM = { "America/Fortaleza" };
const char TZ_AMERICA_FORT_NELSON[] PROGMEM = { "America/Fort_Nelson" };
const char TZ_AMERICA_GLACE_BAY[] PROGMEM = { "America/Glace_Bay" };
const char TZ_AMERICA_GOOSE_BAY[] PROGMEM = { "America/Goose_Bay" };
const char TZ_AMERICA_GRAND_TURK[] PROGMEM = { "America/Grand_Turk" };
const char TZ_AMERICA_GRENADA[] PROGMEM = { "America/Grenada" };
const char TZ_AMERICA_GUADELOUPE[] PROGMEM = { "America/Guadeloupe" };
const char TZ_AMERICA_GUATEMALA[] PROGMEM = { "America/Guatemala" };
const char TZ_AMERICA_GUAYAQUIL[] PROGMEM = { "America/Guayaquil" };
const char TZ_AMERICA_GUYANA[] PROGMEM = { "America/Guyana" };
const char TZ_AMERICA_HALIFAX[] PROGMEM = { "America/Halifax" };
const char TZ_AMERICA_HAVANA[] PROGMEM = { "America/Havana" };
const char TZ_AMERICA_HERMOSILLO[] PROGMEM = { "America/Hermosillo" };
const char TZ_AMERICA_INDIANA_INDIANAPOLIS[] PROGMEM = { "America/Indiana/Indianapolis" };
const char TZ_AMERICA_INDIANA_KNOX[] PROGMEM = { "America/Indiana/Knox" };
const char TZ_AMERICA_INDIANA_MARENGO[] PROGMEM = { "America/Indiana/Marengo" };
const char TZ_AMERICA_INDIANA_PETERSBURG[] PROGMEM = { "America/Indiana/Petersburg" };
const char TZ_AMERICA_INDIANA_TELL_CITY[] PROGMEM = { "America/Indiana/Tell_City" };
const char TZ_AMERICA_INDIANA_VEVAY[] PROGMEM = { "America/Indiana/Vevay" };
const char TZ_AMERICA_INDIANA_VINCENNES[] PROGMEM = { "America/Indiana/Vincennes" };
const char TZ_AMERICA_INDIANA_WINAMAC[] PROGMEM = { "America/Indiana/Winamac" };
const char TZ_AMERICA_INUVIK[] PROGMEM = { "America/Inuvik" };
const char TZ_AMERICA_IQALUIT[] PROGMEM = { "America/Iqaluit" };
const char TZ_AMERICA_JAMAICA[] PROGMEM = { "America/Jamaica" };
const char TZ_AMERICA_JUNEAU[] PROGMEM = { "America/Juneau" };
const char TZ_AMERICA_KENTUCKY_LOUISVILLE[] PROGMEM = { "America/Kentucky/Louisville" };
const char TZ_AMERICA_KENTUCKY_MONTICELLO[] PROGMEM = { "America/Kentucky/Monticello" };
const char TZ_AMERICA_KRALENDIJK[] PROGMEM = { "America/Kralendijk" };
const char TZ_AMERICA_LA_PAZ[] PROGMEM = { "America/La_Paz" };
const char TZ_AMERICA_LIMA[] PROGMEM = { "America/Lima" };
const char TZ_AMERICA_LOS_ANGELES[] PROGMEM = { "America/Los_Angeles" };
const char TZ_AMERICA_LOWER_PRINCES[] PROGMEM = { "America/Lower_Princes" };
const char TZ_AMERICA_MACEIO[] PROGMEM = { "America/Maceio" };
const char TZ_AMERICA_MANAGUA[] PROGMEM = { "America/Managua" };
const char TZ_AMERICA_MANAUS[] PROGMEM = { "America/Manaus" };
const char TZ_AMERICA_MARIGOT[] PROGMEM = { "America/Marigot" };
const char TZ_AMERICA_MARTINIQUE[] PROGMEM = { "America/Martinique" };
const char TZ_AMERICA_MATAMOROS[] PROGMEM = { "America/Matamoros" };
const char TZ_AMERICA_MAZATLAN[] PROGMEM = { "America/Mazatlan" };
const char TZ_AMERICA_MENOMINEE[] PROGMEM = { "America/Menominee" };
const char TZ_AMERICA_MERIDA[] PROGMEM = { "America/Merida" };
const char TZ_AMERICA_METLAKATLA[] PROGMEM = { "America/Metlakatla" };
const char TZ_AMERICA_MEXICO_CITY[] PROGMEM = { "America/Mexico_City" };
const char TZ_AMERICA_MIQUELON[] PROGMEM = { "America/Miquelon" };
const char TZ_AMERICA_MONCTON[] PROGMEM = { "America/Moncton" };
const char TZ_AMERICA_MONTERREY[] PROGMEM = { "America/Monterrey" };
const char TZ_AMERICA_MONTEVIDEO[] PROGMEM = { "America/Montevideo" };
const char TZ_AMERICA_MONTSERRAT[] PROGMEM = { "America/Montserrat" };
const char TZ_AMERICA_NASSAU[] PROGMEM = { "America/Nassau" };
const char TZ_AMERICA_NEW_YORK[] PROGMEM = { "America/New_York" };
const char TZ_AMERICA_NIPIGON[] PROGMEM = { "America/Nipigon" };
const char TZ_AMERICA_NOME[] PROGMEM = { "America/Nome" };
const char TZ_AMERICA_NORONHA[] PROGMEM = { "America/Noronha" };
const char TZ_AMERICA_NORTH_DAKOTA_BEULAH[] PROGMEM = { "America/North_Dakota/Beulah" };
const char TZ_AMERICA_NORTH_DAKOTA_CENTER[] PROGMEM = { "America/North_Dakota/Center" };
const char TZ_AMERICA_NORTH_DAKOTA_NEW_SALEM[] PROGMEM = { "America/North_Dakota/New_Salem" };
const char TZ_AMERICA_NUUK[] PROGMEM = { "America/Nuuk" };
const char TZ_AMERICA_OJINAGA[] PROGMEM = { "America/Ojinaga" };
const char TZ_AMERICA_PANAMA[] PROGMEM = { "America/Panama" };
const char TZ_AMERICA_PANGNIRTUNG[] PROGMEM = { "America/Pangnirtung" };
const char TZ_AMERICA_PARAMARIBO[] PROGMEM = { "America/Paramaribo" };
const char TZ_AMERICA_PHOENIX[] PROGMEM = { "America/Phoenix" };
const char TZ_AMERICA_PORTO_VELHO[] PROGMEM = { "America/Porto_Velho" };
const char TZ_AMERICA_PORT_AU_PRINCE[] PROGMEM = { "America/Port-au-Prince" };
const char TZ_AMERICA_PORT_OF_SPAIN[] PROGMEM = { "America/Port_of_Spain" };
const char TZ_AMERICA_PUERTO_RICO[] PROGMEM = { "America/Puerto_Rico" };
const char TZ_AMERICA_PUNTA_ARENAS[] PROGMEM = { "America/Punta_Arenas" };
const char TZ_AMERICA_RAINY_RIVER[] PROGMEM = { "America/Rainy_River" };
const char TZ_AMERICA_RANKIN_INLET[] PROGMEM = { "America/Rankin_Inlet" };
const char TZ_AMERICA_RECIFE[] PROGMEM = { "America/Recife" };
const char TZ_AMERICA_REGINA[] PROGMEM = { "America/Regina" };
const char TZ_AMERICA_RESOLUTE[] PROGMEM = { "America/Resolute" };
const char TZ_AMERICA_RIO_BRANCO[] PROGMEM = { "America/Rio_Branco" };
const char TZ_AMERICA_SANTAREM[] PROGMEM = { "America/Santarem" };
const char TZ_AMERICA_SANTIAGO[] PROGMEM = { "America/Santiago" };
const char TZ_AMERICA_SANTO_DOMINGO[] PROGMEM = { "America/Santo_Domingo" };
const char TZ_AMERICA_SAO_PAULO[] PROGMEM = { "America/Sao_Paulo" };
const char TZ_AMERICA_SCORESBYSUND[] PROGMEM = { "America/Scoresbysund" };
const char TZ_AMERICA_SITKA[] PROGMEM = { "America/Sitka" };
const char TZ_AMERICA_ST_BARTHELEMY[] PROGMEM = { "America/St_Barthelemy" };
const char TZ_AMERICA_ST_JOHNS[] PROGMEM = { "America/St_Johns" };
const char TZ_AMERICA_ST_KITTS[] PROGMEM = { "America/St_Kitts" };
const char TZ_AMERICA_ST_LUCIA[] PROGMEM = { "America/St_Lucia" };
const char TZ_AMERICA_ST_THOMAS[] PROGMEM = { "America/St_Thomas" };
const char TZ_AMERICA_ST_VINCENT[] PROGMEM = { "America/St_Vincent" };
const char TZ_AMERICA_SWIFT_CURRENT[] PROGMEM = { "America/Swift_Current" };
const char TZ_AMERICA_TEGUCIGALPA[] PROGMEM = { "America/Tegucigalpa" };
const char TZ_AMERICA_THULE[] PROGMEM = { "America/Thule" };
const char TZ_AMERICA_THUNDER_BAY[] PROGMEM = { "America/Thunder_Bay" };
const char TZ_AMERICA_TIJUANA[] PROGMEM = { "America/Tijuana" };
const char TZ_AMERICA_TORONTO[] PROGMEM = { "America/Toronto" };
const char TZ_AMERICA_TORTOLA[] PROGMEM = { "America/Tortola" };
const char TZ_AMERICA_VANCOUVER[] PROGMEM = { "America/Vancouver" };
const char TZ_AMERICA_WHITEHORSE[] PROGMEM = { "America/Whitehorse" };
const char TZ_AMERICA_WINNIPEG[] PROGMEM = { "America/Winnipeg" };
const char TZ_AMERICA_YAKUTAT[] PROGMEM = { "America/Yakutat" };
const char TZ_AMERICA_YELLOWKNIFE[] PROGMEM = { "America/Yellowknife" };
const char TZ_ANTARCTICA_CASEY[] PROGMEM = { "Antarctica/Casey" };
const char TZ_ANTARCTICA_DAVIS[] PROGMEM = { "Antarctica/Davis" };
const char TZ_ANTARCTICA_DUMONTDURVILLE[] PROGMEM = { "Antarctica/DumontDUrville" };
const char TZ_ANTARCTICA_MACQUARIE[] PROGMEM = { "Antarctica/Macquarie" };
const char TZ_ANTARCTICA_MAWSON[] PROGMEM = { "Antarctica/Mawson" };
const char TZ_ANTARCTICA_MCMURDO[] PROGMEM = { "Antarctica/McMurdo" };
const char TZ_ANTARCTICA_PALMER[] PROGMEM = { "Antarctica/Palmer" };
const char TZ_ANTARCTICA_ROTHERA[] PROGMEM = { "Antarctica/Rothera" };
const char TZ_ANTARCTICA_SYOWA[] PROGMEM = { "Antarctica/Syowa" };
const char TZ_ANTARCTICA_TROLL[] PROGMEM = { "Antarctica/Troll" };
const char TZ_ANTARCTICA_VOSTOK[] PROGMEM = { "Antarctica/Vostok" };
const char TZ_ARCTIC_LONGYEARBYEN[] PROGMEM = { "Arctic/Longyearbyen" };
const char TZ_ASIA_ADEN[] PROGMEM = { "Asia/Aden" };
const char TZ_ASIA_ALMATY[] PROGMEM = { "Asia/Almaty" };
const char TZ_ASIA_AMMAN[] PROGMEM = { "Asia/Amman" };
const char TZ_ASIA_ANADYR[] PROGMEM = { "Asia/Anadyr" };
const char TZ_ASIA_AQTAU[] PROGMEM = { "Asia/Aqtau" };
const char TZ_ASIA_AQTOBE[] PROGMEM = { "Asia/Aqtobe" };
const char TZ_ASIA_ASHGABAT[] PROGMEM = { "Asia/Ashgabat" };
const char TZ_ASIA_ATYRAU[] PROGMEM = { "Asia/Atyrau" };
const char TZ_ASIA_BAGHDAD[] PROGMEM = { "Asia/Baghdad" };
const char TZ_ASIA_BAHRAIN[] PROGMEM = { "Asia/Bahrain" };
const char TZ_ASIA_BAKU[] PROGMEM = { "Asia/Baku" };
const char TZ_ASIA_BANGKOK[] PROGMEM = { "Asia/Bangkok" };
const char TZ_ASIA_BARNAUL[] PROGMEM = { "Asia/Barnaul" };
const char TZ_ASIA_BEIRUT[] PROGMEM = { "Asia/Beirut" };
const char TZ_ASIA_BISHKEK[] PROGMEM = { "Asia/Bishkek" };
const char TZ_ASIA_BRUNEI[] PROGMEM = { "Asia/Brunei" };
const char TZ_ASIA_CHITA[] PROGMEM = { "Asia/Chita" };
const char TZ_ASIA_CHOIBALSAN[] PROGMEM = { "Asia/Choibalsan" };
const char TZ_ASIA_COLOMBO[] PROGMEM = { "Asia/Colombo" };
const char TZ_ASIA_DAMASCUS[] PROGMEM = { "Asia/Damascus" };
const char TZ_ASIA_DHAKA[] PROGMEM = { "Asia/Dhaka" };
const char TZ_ASIA_DILI[] PROGMEM = { "Asia/Dili" };
const char TZ_ASIA_DUBAI[] PROGMEM = { "Asia/Dubai" };
const char TZ_ASIA_DUSHANBE[] PROGMEM = { "Asia/Dushanbe" };
const char TZ_ASIA_FAMAGUSTA[] PROGMEM = { "Asia/Famagusta" };
const char TZ_ASIA_GAZA[] PROGMEM = { "Asia/Gaza" };
const char TZ_ASIA_HEBRON[] PROGMEM = { "Asia/Hebron" };
const char TZ_ASIA_HONG_KONG[] PROGMEM = { "Asia/Hong_Kong" };
const char TZ_ASIA_HOVD[] PROGMEM = { "Asia/Hovd" };
const char TZ_ASIA_HO_CHI_MINH[] PROGMEM = { "Asia/Ho_Chi_Minh" };
const char TZ_ASIA_IRKUTSK[] PROGMEM = { "Asia/Irkutsk" };
const char TZ_ASIA_ISTANBUL[] PROGMEM = { "Asia/Istanbul" };
const char TZ_ASIA_JAKARTA[] PROGMEM = { "Asia/Jakarta" };
const char TZ_ASIA_JAYAPURA[] PROGMEM = { "Asia/Jayapura" };
const char TZ_ASIA_JERUSALEM[] PROGMEM = { "Asia/Jerusalem" };
const char TZ_ASIA_KABUL[] PROGMEM = { "Asia/Kabul" };
const char TZ_ASIA_KAMCHATKA[] PROGMEM = { "Asia/Kamchatka" };
const char TZ_ASIA_KARACHI[] PROGMEM = { "Asia/Karachi" };
const char TZ_ASIA_KATHMANDU[] PROGMEM = { "Asia/Kathmandu" };
const char TZ_ASIA_KHANDYGA[] PROGMEM = { "Asia/Khandyga" };
const char TZ_ASIA_KOLKATA[] PROGMEM = { "Asia/Kolkata" };
const char TZ_ASIA_KRASNOYARSK[] PROGMEM = { "Asia/Krasnoyarsk" };
const char TZ_ASIA_KUALA_LUMPUR[] PROGMEM = { "Asia/Kuala_Lumpur" };
const char TZ_ASIA_KUCHING[] PROGMEM = { "Asia/Kuching" };
const char TZ_ASIA_KUWAIT[] PROGMEM = { "Asia/Kuwait" };
const char TZ_ASIA_MACAU[] PROGMEM = { "Asia/Macau" };
const char TZ_ASIA_MAGADAN[] PROGMEM = { "Asia/Magadan" };
const char TZ_ASIA_MAKASSAR[] PROGMEM = { "Asia/Makassar" };
const char TZ_ASIA_MANILA[] PROGMEM = { "Asia/Manila" };
const char TZ_ASIA_MUSCAT[] PROGMEM = { "Asia/Muscat" };
const char TZ_ASIA_NICOSIA[] PROGMEM = { "Asia/Nicosia" };
const char TZ_ASIA_NOVOKUZNETSK[] PROGMEM = { "Asia/Novokuznetsk" };
const char TZ_ASIA_NOVOSIBIRSK[] PROGMEM = { "Asia/Novosibirsk" };
const char TZ_ASIA_OMSK[] PROGMEM = { "Asia/Omsk" };
const char TZ_ASIA_ORAL[] PROGMEM = { "Asia/Oral" };
const char TZ_ASIA_PHNOM_PENH[] PROGMEM = { "Asia/Phnom_Penh" };
const char TZ_ASIA_PONTIANAK[] PROGMEM = { "Asia/Pontianak" };
const char TZ_ASIA_PYONGYANG[] PROGMEM = { "Asia/Pyongyang" };
const char TZ_ASIA_QATAR[] PROGMEM = { "Asia/Qatar" };
const char TZ_ASIA_QOSTANAY[] PROGMEM = { "Asia/Qostanay" };
const char TZ_ASIA_QYZYLORDA[] PROGMEM = { "Asia/Qyzylorda" };
const char TZ_ASIA_RIYADH[] PROGMEM = { "Asia/Riyadh" };
const char TZ_ASIA_SAKHALIN[] PROGMEM = { "Asia/Sakhalin" };
const char TZ_ASIA_SAMARKAND[] PROGMEM = { "Asia/Samarkand" };
const char TZ_ASIA_SEOUL[] PROGMEM = { "Asia/Seoul" };
const char TZ_ASIA_SHANGHAI[] PROGMEM = { "Asia/Shanghai" };
const char TZ_ASIA_SINGAPORE[] PROGMEM = { "Asia/Singapore" };
const char TZ_ASIA_SREDNEKOLYMSK[] PROGMEM = { "Asia/Srednekolymsk" };
const char TZ_ASIA_TAIPEI[] PROGMEM = { "Asia/Taipei" };
const char TZ_ASIA_TASHKENT[] PROGMEM = { "Asia/Tashkent" };
const char TZ_ASIA_TBILISI[] PROGMEM = { "Asia/Tbilisi" };
const char TZ_ASIA_TEHRAN[] PROGMEM = { "Asia/Tehran" };
const char TZ_ASIA_THIMPHU[] PROGMEM = { "Asia/Thimphu" };
const char TZ_ASIA_TOKYO[] PROGMEM = { "Asia/Tokyo" };
const char TZ_ASIA_TOMSK[] PROGMEM = { "Asia/Tomsk" };
const char TZ_ASIA_ULAANBAATAR[] PROGMEM = { "Asia/Ulaanbaatar" };
const char TZ_ASIA_URUMQI[] PROGMEM = { "Asia/Urumqi" };
const char TZ_ASIA_UST_NERA[] PROGMEM = { "Asia/Ust-Nera" };
const char TZ_ASIA_VIENTIANE[] PROGMEM = { "Asia/Vientiane" };
const char TZ_ASIA_VLADIVOSTOK[] PROGMEM = { "Asia/Vladivostok" };
const char TZ_ASIA_YAKUTSK[] PROGMEM = { "Asia/Yakutsk" };
const char TZ_ASIA_YANGON[] PROGMEM = { "Asia/Yangon" };
const char TZ_ASIA_YEKATERINBURG[] PROGMEM = { "Asia/Yekaterinburg" };
const char TZ_ASIA_YEREVAN[] PROGMEM = { "Asia/Yerevan" };
const char TZ_ATLANTIC_AZORES[] PROGMEM = { "Atlantic/Azores" };
const char TZ_ATLANTIC_BERMUDA[] PROGMEM = { "Atlantic/Bermuda" };
const char TZ_ATLANTIC_CANARY[] PROGMEM = { "Atlantic/Canary" };
const char TZ_ATLANTIC_CAPE_VERDE[] PROGMEM = { "Atlantic/Cape_Verde" };
const char TZ_ATLANTIC_FAROE[] PROGMEM = { "Atlantic/Faroe" };
const char TZ_ATLANTIC_MADEIRA[] PROGMEM = { "Atlantic/Madeira" };
const char TZ_ATLANTIC_REYKJAVIK[] PROGMEM = { "Atlantic/Reykjavik" };
const char TZ_ATLANTIC_SOUTH_GEORGIA[] PROGMEM = { "Atlantic/South_Georgia" };
const char TZ_ATLANTIC_STANLEY[] PROGMEM = { "Atlantic/Stanley" };
const char TZ_ATLANTIC_ST_HELENA[] PROGMEM = { "Atlantic/St_Helena" };
const char TZ_AUSTRALIA_ADELAIDE[] PROGMEM = { "Australia/Adelaide" };
const char TZ_AUSTRALIA_BRISBANE[] PROGMEM = { "Australia/Brisbane" };
const char TZ_AUSTRALIA_BROKEN_HILL[] PROGMEM = { "Australia/Broken_Hill" };
const char TZ_AUSTRALIA_DARWIN[] PROGMEM = { "Australia/Darwin" };
const char TZ_AUSTRALIA_EUCLA[] PROGMEM = { "Australia/Eucla" };
const char TZ_AUSTRALIA_HOBART[] PROGMEM = { "Australia/Hobart" };
const char TZ_AUSTRALIA_LINDEMAN[] PROGMEM = { "Australia/Lindeman" };
const char TZ_AUSTRALIA_LORD_HOWE[] PROGMEM = { "Australia/Lord_Howe" };
const char TZ_AUSTRALIA_MELBOURNE[] PROGMEM = { "Australia/Melbourne" };
const char TZ_AUSTRALIA_PERTH[] PROGMEM = { "Australia/Perth" };
const char TZ_AUSTRALIA_SYDNEY[] PROGMEM = { "Australia/Sydney" };
const char TZ_EUROPE_AMSTERDAM[] PROGMEM = { "Europe/Amsterdam" };
const char TZ_EUROPE_ANDORRA[] PROGMEM = { "Europe/Andorra" };
const char TZ_EUROPE_ASTRAKHAN[] PROGMEM = { "Europe/Astrakhan" };
const char TZ_EUROPE_ATHENS[] PROGMEM = { "Europe/Athens" };
const char TZ_EUROPE_BELGRADE[] PROGMEM = { "Europe/Belgrade" };
const char TZ_EUROPE_BERLIN[] PROGMEM = { "Europe/Berlin" };
const char TZ_EUROPE_BRATISLAVA[] PROGMEM = { "Europe/Bratislava" };
const char TZ_EUROPE_BRUSSELS[] PROGMEM = { "Europe/Brussels" };
const char TZ_EUROPE_BUCHAREST[] PROGMEM = { "Europe/Bucharest" };
const char TZ_EUROPE_BUDAPEST[] PROGMEM = { "Europe/Budapest" };
const char TZ_EUROPE_BUSINGEN[] PROGMEM = { "Europe/Busingen" };
const char TZ_EUROPE_CHISINAU[] PROGMEM = { "Europe/Chisinau" };
const char TZ_EUROPE_COPENHAGEN[] PROGMEM = { "Europe/Copenhagen" };
const char TZ_EUROPE_DUBLIN[] PROGMEM = { "Europe/Dublin" };
const char TZ_EUROPE_GIBRALTAR[] PROGMEM = { "Europe/Gibraltar" };
const char TZ_EUROPE_GUERNSEY[] PROGMEM = { "Europe/Guernsey" };
const char TZ_EUROPE_HELSINKI[] PROGMEM = { "Europe/Helsinki" };
const char TZ_EUROPE_ISLE_OF_MAN[] PROGMEM = { "Europe/Isle_of_Man" };
const char TZ_EUROPE_ISTANBUL[] PROGMEM = { "Europe/Istanbul" };
const char TZ_EUROPE_JERSEY[] PROGMEM = { "Europe/Jersey" };
const char TZ_EUROPE_KALININGRAD[] PROGMEM = { "Europe/Kaliningrad" };
const char TZ_EUROPE_KIEV[] PROGMEM = { "Europe/Kiev" };
const char TZ_EUROPE_KIROV[] PROGMEM = { "Europe/Kirov" };
const char TZ_EUROPE_LISBON[] PROGMEM = { "Europe/Lisbon" };
const char TZ_EUROPE_LJUBLJANA[] PROGMEM = { "Europe/Ljubljana" };
const char TZ_EUROPE_LONDON[] PROGMEM = { "Europe/London" };
const char TZ_EUROPE_LUXEMBOURG[] PROGMEM = { "Europe/Luxembourg" };
const char TZ_EUROPE_MADRID[] PROGMEM = { "Europe/Madrid" };
const char TZ_EUROPE_MALTA[] PROGMEM = { "Europe/Malta" };
const char TZ_EUROPE_MARIEHAMN[] PROGMEM = { "Europe/Mariehamn" };
const char TZ_EUROPE_MINSK[] PROGMEM = { "Europe/Minsk" };
const char TZ_EUROPE_MONACO[] PROGMEM = { "Europe/Monaco" };
const char TZ_EUROPE_MOSCOW[] PROGMEM = { "Europe/Moscow" };
const char TZ_EUROPE_NICOSIA[] PROGMEM = { "Europe/Nicosia" };
const char TZ_EUROPE_OSLO[] PROGMEM = { "Europe/Oslo" };
const char TZ_EUROPE_PARIS[] PROGMEM = { "Europe/Paris" };
const char TZ_EUROPE_PODGORICA[] PROGMEM = { "Europe/Podgorica" };
const char TZ_EUROPE_PRAGUE[] PROGMEM = { "Europe/Prague" };
const char TZ_EUROPE_RIGA[] PROGMEM = { "Europe/Riga" };
const char TZ_EUROPE_ROME[] PROGMEM = { "Europe/Rome" };
const char TZ_EUROPE_SAMARA[] PROGMEM = { "Europe/Samara" };
const char TZ_EUROPE_SAN_MARINO[] PROGMEM = { "Europe/San_Marino" };
const char TZ_EUROPE_SARAJEVO[] PROGMEM = { "Europe/Sarajevo" };
const char TZ_EUROPE_SARATOV[] PROGMEM = { "Europe/Saratov" };
const char TZ_EUROPE_SIMFEROPOL[] PROGMEM = { "Europe/Simferopol" };
const char TZ_EUROPE_SKOPJE[] PROGMEM = { "Europe/Skopje" };
const char TZ_EUROPE_SOFIA[] PROGMEM = { "Europe/Sofia" };
const char TZ_EUROPE_STOCKHOLM[] PROGMEM = { "Europe/Stockholm" };
const char TZ_EUROPE_TALLINN[] PROGMEM = { "Europe/Tallinn" };
const char TZ_EUROPE_TIRANE[] PROGMEM = { "Europe/Tirane" };
const char TZ_EUROPE_ULYANOVSK[] PROGMEM = { "Europe/Ulyanovsk" };
const char TZ_EUROPE_UZHGOROD[] PROGMEM = { "Europe/Uzhgorod" };
const char TZ_EUROPE_VADUZ[] PROGMEM = { "Europe/Vaduz" };
const char TZ_EUROPE_VATICAN[] PROGMEM = { "Europe/Vatican" };
const char TZ_EUROPE_VIENNA[] PROGMEM = { "Europe/Vienna" };
const char TZ_EUROPE_VILNIUS[] PROGMEM = { "Europe/Vilnius" };
const char TZ_EUROPE_VOLGOGRAD[] PROGMEM = { "Europe/Volgograd" };
const char TZ_EUROPE_WARSAW[] PROGMEM = { "Europe/Warsaw" };
const char TZ_EUROPE_ZAGREB[] PROGMEM = { "Europe/Zagreb" };
const char TZ_EUROPE_ZAPOROZHYE[] PROGMEM = { "Europe/Zaporozhye" };
const char TZ_EUROPE_ZURICH[] PROGMEM = { "Europe/Zurich" };
const char TZ_INDIAN_ANTANANARIVO[] PROGMEM = { "Indian/Antananarivo" };
const char TZ_INDIAN_CHAGOS[] PROGMEM = { "Indian/Chagos" };
const char TZ_INDIAN_CHRISTMAS[] PROGMEM = { "Indian/Christmas" };
const char TZ_INDIAN_COCOS[] PROGMEM = { "Indian/Cocos" };
const char TZ_INDIAN_COMORO[] PROGMEM = { "Indian/Comoro" };
const char TZ_INDIAN_KERGUELEN[] PROGMEM = { "Indian/Kerguelen" };
const char TZ_INDIAN_MAHE[] PROGMEM = { "Indian/Mahe" };
const char TZ_INDIAN_MALDIVES[] PROGMEM = { "Indian/Maldives" };
const char TZ_INDIAN_MAURITIUS[] PROGMEM = { "Indian/Mauritius" };
const char TZ_INDIAN_MAYOTTE[] PROGMEM = { "Indian/Mayotte" };
const char TZ_INDIAN_REUNION[] PROGMEM = { "Indian/Reunion" };
const char TZ_PACIFIC_APIA[] PROGMEM = { "Pacific/Apia" };
const char TZ_PACIFIC_AUCKLAND[] PROGMEM = { "Pacific/Auckland" };
const char TZ_PACIFIC_BOUGAINVILLE[] PROGMEM = { "Pacific/Bougainville" };
const char TZ_PACIFIC_CHATHAM[] PROGMEM = { "Pacific/Chatham" };
const char TZ_PACIFIC_CHUUK[] PROGMEM = { "Pacific/Chuuk" };
const char TZ_PACIFIC_EASTER[] PROGMEM = { "Pacific/Easter" };
const char TZ_PACIFIC_EFATE[] PROGMEM = { "Pacific/Efate" };
const char TZ_PACIFIC_ENDERBURY[] PROGMEM = { "Pacific/Enderbury" };
const char TZ_PACIFIC_FAKAOFO[] PROGMEM = { "Pacific/Fakaofo" };
const char TZ_PACIFIC_FIJI[] PROGMEM = { "Pacific/Fiji" };
const char TZ_PACIFIC_FUNAFUTI[] PROGMEM = { "Pacific/Funafuti" };
const char TZ_PACIFIC_GALAPAGOS[] PROGMEM = { "Pacific/Galapagos" };
const char TZ_PACIFIC_GAMBIER[] PROGMEM = { "Pacific/Gambier" };
const char TZ_PACIFIC_GUADALCANAL[] PROGMEM = { "Pacific/Guadalcanal" };
const char TZ_PACIFIC_GUAM[] PROGMEM = { "Pacific/Guam" };
const char TZ_PACIFIC_HONOLULU[] PROGMEM = { "Pacific/Honolulu" };
const char TZ_PACIFIC_KIRITIMATI[] PROGMEM = { "Pacific/Kiritimati" };
const char TZ_PACIFIC_KOSRAE[] PROGMEM = { "Pacific/Kosrae" };
const char TZ_PACIFIC_KWAJALEIN[] PROGMEM = { "Pacific/Kwajalein" };
const char TZ_PACIFIC_MAJURO[] PROGMEM = { "Pacific/Majuro" };
const char TZ_PACIFIC_MARQUESAS[] PROGMEM = { "Pacific/Marquesas" };
const char TZ_PACIFIC_MIDWAY[] PROGMEM = { "Pacific/Midway" };
const char TZ_PACIFIC_NAURU[] PROGMEM = { "Pacific/Nauru" };
const char TZ_PACIFIC_NIUE[] PROGMEM = { "Pacific/Niue" };
const char TZ_PACIFIC_NORFOLK[] PROGMEM = { "Pacific/Norfolk" };
const char TZ_PACIFIC_NOUMEA[] PROGMEM = { "Pacific/Noumea" };
const char TZ_PACIFIC_PAGO_PAGO[] PROGMEM = { "Pacific/Pago_Pago" };
const char TZ_PACIFIC_PALAU[] PROGMEM = { "Pacific/Palau" };
const char TZ_PACIFIC_PITCAIRN[] PROGMEM = { "Pacific/Pitcairn" };
const char TZ_PACIFIC_POHNPEI[] PROGMEM = { "Pacific/Pohnpei" };
const char TZ_PACIFIC_PORT_MORESBY[] PROGMEM = { "Pacific/Port_Moresby" };
const char TZ_PACIFIC_RAROTONGA[] PROGMEM = { "Pacific/Rarotonga" };
const char TZ_PACIFIC_SAIPAN[] PROGMEM = { "Pacific/Saipan" };
const char TZ_PACIFIC_TAHITI[] PROGMEM = { "Pacific/Tahiti" };
const char TZ_PACIFIC_TARAWA[] PROGMEM = { "Pacific/Tarawa" };
const char TZ_PACIFIC_TONGATAPU[] PROGMEM = { "Pacific/Tongatapu" };
const char TZ_PACIFIC_WAKE[] PROGMEM = { "Pacific/Wake" };
const char TZ_PACIFIC_WALLIS[] PROGMEM = { "Pacific/Wallis" };


const TimeZoneRules TimeZonesTable[] PROGMEM = {
    { TZ_UTC, 0, 0, 0, 0, 0, 0, TZ_UTC, 0, 0, 0, 0, 0, 0, TZ_UTC },
    { TZ_AFRICA_ABIDJAN, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_ACCRA, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_ADDIS_ABABA, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_ALGIERS, 60, 0, 0, 0, 0, 0, TZ_CET, 60, 0, 0, 0, 0, 0, TZ_CET },
    { TZ_AFRICA_ASMARA, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_BAMAKO, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_BANGUI, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_BANJUL, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_BISSAU, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_BLANTYRE, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_BRAZZAVILLE, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_BUJUMBURA, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_CAIRO, 120, 0, 0, 0, 0, 0, TZ_EET, 120, 0, 0, 0, 0, 0, TZ_EET },
    { TZ_AFRICA_CASABLANCA, 60, M_APR, 0, 11, 3, 0, TZ_P01_P00, 120, M_MAY, 0, 16, 2, 0, TZ_P01_P00 },
    { TZ_AFRICA_CEUTA, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_AFRICA_CONAKRY, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_DAKAR, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_DAR_ES_SALAAM, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_DJIBOUTI, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_DOUALA, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_EL_AAIUN, 60, M_APR, 0, 11, 3, 0, TZ_P01_P00, 120, M_MAY, 0, 16, 2, 0, TZ_P01_P00 },
    { TZ_AFRICA_FREETOWN, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_GABORONE, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_HARARE, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_JOHANNESBURG, 120, 0, 0, 0, 0, 0, TZ_SAST, 120, 0, 0, 0, 0, 0, TZ_SAST },
    { TZ_AFRICA_JUBA, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_KAMPALA, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_KHARTOUM, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_KIGALI, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_KINSHASA, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_LAGOS, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_LIBREVILLE, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_LOME, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_LUANDA, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_LUBUMBASHI, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_LUSAKA, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_MALABO, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_MAPUTO, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AFRICA_MASERU, 120, 0, 0, 0, 0, 0, TZ_SAST, 120, 0, 0, 0, 0, 0, TZ_SAST },
    { TZ_AFRICA_MBABANE, 120, 0, 0, 0, 0, 0, TZ_SAST, 120, 0, 0, 0, 0, 0, TZ_SAST },
    { TZ_AFRICA_MOGADISHU, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_MONROVIA, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_NAIROBI, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_AFRICA_NDJAMENA, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_NIAMEY, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_NOUAKCHOTT, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_OUAGADOUGOU, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_PORTO_NOVO, 60, 0, 0, 0, 0, 0, TZ_WAT, 60, 0, 0, 0, 0, 0, TZ_WAT },
    { TZ_AFRICA_SAO_TOME, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AFRICA_TRIPOLI, 120, 0, 0, 0, 0, 0, TZ_EET, 120, 0, 0, 0, 0, 0, TZ_EET },
    { TZ_AFRICA_TUNIS, 60, 0, 0, 0, 0, 0, TZ_CET, 60, 0, 0, 0, 0, 0, TZ_CET },
    { TZ_AFRICA_WINDHOEK, 120, 0, 0, 0, 0, 0, TZ_CAT, 120, 0, 0, 0, 0, 0, TZ_CAT },
    { TZ_AMERICA_ADAK, -600, M_NOV, 1, D_SUN, 2, 0, TZ_HST, -540, M_MAR, 2, D_SUN, 2, 0, TZ_HDT },
    { TZ_AMERICA_ANCHORAGE, -540, M_NOV, 1, D_SUN, 2, 0, TZ_AKST, -480, M_MAR, 2, D_SUN, 2, 0, TZ_AKDT },
    { TZ_AMERICA_ANGUILLA, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_ANTIGUA, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_ARAGUAINA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_BUENOS_AIRES, -180, 0, 0, 0, 0, 0, TZ_M03_M02, -180, 0, 0, 0, 0, 0, TZ_M03_M02 },
    { TZ_AMERICA_ARGENTINA_CATAMARCA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_CORDOBA, -180, 0, 0, 0, 0, 0, TZ_M03_M02, -180, 0, 0, 0, 0, 0, TZ_M03_M02 },
    { TZ_AMERICA_ARGENTINA_JUJUY, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_LA_RIOJA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_MENDOZA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_RIO_GALLEGOS, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_SALTA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_SAN_JUAN, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_SAN_LUIS, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARGENTINA_TUCUMAN, -180, 0, 0, 0, 0, 0, TZ_M03_M02, -180, 0, 0, 0, 0, 0, TZ_M03_M02 },
    { TZ_AMERICA_ARGENTINA_USHUAIA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_ARUBA, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_ASUNCION, -240, M_MAR, 4, D_SUN, 0, 0, TZ_M04_M03, -180, M_OCT, 1, D_SUN, 0, 0, TZ_M04_M03 },
    { TZ_AMERICA_ATIKOKAN, -300, 0, 0, 0, 0, 0, TZ_EST, -300, 0, 0, 0, 0, 0, TZ_EST },
    { TZ_AMERICA_BAHIA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_BAHIA_BANDERAS, -360, M_OCT, 5, D_SUN, 2, 0, TZ_CST, -300, M_APR, 1, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_BARBADOS, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_BELEM, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_BELIZE, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_BLANC_SABLON, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_BOA_VISTA, -240, 0, 0, 0, 0, 0, TZ_M04, -240, 0, 0, 0, 0, 0, TZ_M04 },
    { TZ_AMERICA_BOGOTA, -300, 0, 0, 0, 0, 0, TZ_M05_M04, -300, 0, 0, 0, 0, 0, TZ_M05_M04 },
    { TZ_AMERICA_BOISE, -420, M_NOV, 1, D_SUN, 2, 0, TZ_MST, -360, M_MAR, 2, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_CAMBRIDGE_BAY, -420, M_NOV, 1, D_SUN, 2, 0, TZ_MST, -360, M_MAR, 2, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_CAMPO_GRANDE, -240, 0, 0, 0, 0, 0, TZ_M04_M03, -240, 0, 0, 0, 0, 0, TZ_M04_M03 },
    { TZ_AMERICA_CANCUN, -300, 0, 0, 0, 0, 0, TZ_EST, -300, 0, 0, 0, 0, 0, TZ_EST },
    { TZ_AMERICA_CARACAS, -240, 0, 0, 0, 0, 0, TZ_M04, -240, 0, 0, 0, 0, 0, TZ_M04 },
    { TZ_AMERICA_CAYENNE, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_CAYMAN, -300, 0, 0, 0, 0, 0, TZ_EST, -300, 0, 0, 0, 0, 0, TZ_EST },
    { TZ_AMERICA_CHICAGO, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_CHIHUAHUA, -420, M_OCT, 5, D_SUN, 2, 0, TZ_MST, -360, M_APR, 1, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_COSTA_RICA, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_CRESTON, -420, 0, 0, 0, 0, 0, TZ_MST, -420, 0, 0, 0, 0, 0, TZ_MST },
    { TZ_AMERICA_CUIABA, -240, 0, 0, 0, 0, 0, TZ_M04_M03, -240, 0, 0, 0, 0, 0, TZ_M04_M03 },
    { TZ_AMERICA_CURACAO, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_DANMARKSHAVN, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AMERICA_DAWSON, -420, 0, 0, 0, 0, 0, TZ_MST, -420, 0, 0, 0, 0, 0, TZ_MST },
    { TZ_AMERICA_DAWSON_CREEK, -420, 0, 0, 0, 0, 0, TZ_MST, -420, 0, 0, 0, 0, 0, TZ_MST },
    { TZ_AMERICA_DENVER, -420, M_NOV, 1, D_SUN, 2, 0, TZ_MST, -360, M_MAR, 2, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_DETROIT, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_DOMINICA, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_EDMONTON, -420, M_NOV, 1, D_SUN, 2, 0, TZ_MST, -360, M_MAR, 2, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_EIRUNEPE, -300, 0, 0, 0, 0, 0, TZ_M05, -300, 0, 0, 0, 0, 0, TZ_M05 },
    { TZ_AMERICA_EL_SALVADOR, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_FORTALEZA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_FORT_NELSON, -420, 0, 0, 0, 0, 0, TZ_MST, -420, 0, 0, 0, 0, 0, TZ_MST },
    { TZ_AMERICA_GLACE_BAY, -240, M_NOV, 1, D_SUN, 2, 0, TZ_AST, -180, M_MAR, 2, D_SUN, 2, 0, TZ_ADT },
    { TZ_AMERICA_GOOSE_BAY, -240, M_NOV, 1, D_SUN, 2, 0, TZ_AST, -180, M_MAR, 2, D_SUN, 2, 0, TZ_ADT },
    { TZ_AMERICA_GRAND_TURK, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_GRENADA, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_GUADELOUPE, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_GUATEMALA, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_GUAYAQUIL, -300, 0, 0, 0, 0, 0, TZ_M05_M04, -300, 0, 0, 0, 0, 0, TZ_M05_M04 },
    { TZ_AMERICA_GUYANA, -240, 0, 0, 0, 0, 0, TZ_M04, -240, 0, 0, 0, 0, 0, TZ_M04 },
    { TZ_AMERICA_HALIFAX, -240, M_NOV, 1, D_SUN, 2, 0, TZ_AST, -180, M_MAR, 2, D_SUN, 2, 0, TZ_ADT },
    { TZ_AMERICA_HAVANA, -300, M_NOV, 1, D_SUN, 1, 0, TZ_CST, -240, M_MAR, 2, D_SUN, 0, 0, TZ_CDT },
    { TZ_AMERICA_HERMOSILLO, -420, 0, 0, 0, 0, 0, TZ_MST, -420, 0, 0, 0, 0, 0, TZ_MST },
    { TZ_AMERICA_INDIANA_INDIANAPOLIS, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_INDIANA_KNOX, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_INDIANA_MARENGO, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_INDIANA_PETERSBURG, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_INDIANA_TELL_CITY, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_INDIANA_VEVAY, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_INDIANA_VINCENNES, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_INDIANA_WINAMAC, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_INUVIK, -420, M_NOV, 1, D_SUN, 2, 0, TZ_MST, -360, M_MAR, 2, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_IQALUIT, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_JAMAICA, -300, 0, 0, 0, 0, 0, TZ_EST, -300, 0, 0, 0, 0, 0, TZ_EST },
    { TZ_AMERICA_JUNEAU, -540, M_NOV, 1, D_SUN, 2, 0, TZ_AKST, -480, M_MAR, 2, D_SUN, 2, 0, TZ_AKDT },
    { TZ_AMERICA_KENTUCKY_LOUISVILLE, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_KENTUCKY_MONTICELLO, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_KRALENDIJK, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_LA_PAZ, -240, 0, 0, 0, 0, 0, TZ_M04, -240, 0, 0, 0, 0, 0, TZ_M04 },
    { TZ_AMERICA_LIMA, -300, 0, 0, 0, 0, 0, TZ_M05_M04, -300, 0, 0, 0, 0, 0, TZ_M05_M04 },
    { TZ_AMERICA_LOS_ANGELES, -480, M_NOV, 1, D_SUN, 2, 0, TZ_PST, -420, M_MAR, 2, D_SUN, 2, 0, TZ_PDT },
    { TZ_AMERICA_LOWER_PRINCES, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_MACEIO, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_MANAGUA, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_MANAUS, -240, 0, 0, 0, 0, 0, TZ_M04, -240, 0, 0, 0, 0, 0, TZ_M04 },
    { TZ_AMERICA_MARIGOT, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_MARTINIQUE, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_MATAMOROS, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_MAZATLAN, -420, M_OCT, 5, D_SUN, 2, 0, TZ_MST, -360, M_APR, 1, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_MENOMINEE, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_MERIDA, -360, M_OCT, 5, D_SUN, 2, 0, TZ_CST, -300, M_APR, 1, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_METLAKATLA, -540, M_NOV, 1, D_SUN, 2, 0, TZ_AKST, -480, M_MAR, 2, D_SUN, 2, 0, TZ_AKDT },
    { TZ_AMERICA_MEXICO_CITY, -360, M_OCT, 5, D_SUN, 2, 0, TZ_CST, -300, M_APR, 1, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_MIQUELON, -180, M_NOV, 1, D_SUN, 2, 0, TZ_M03_M02, -120, M_MAR, 2, D_SUN, 2, 0, TZ_M03_M02 },
    { TZ_AMERICA_MONCTON, -240, M_NOV, 1, D_SUN, 2, 0, TZ_AST, -180, M_MAR, 2, D_SUN, 2, 0, TZ_ADT },
    { TZ_AMERICA_MONTERREY, -360, M_OCT, 5, D_SUN, 2, 0, TZ_CST, -300, M_APR, 1, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_MONTEVIDEO, -180, 0, 0, 0, 0, 0, TZ_M03_M02, -180, 0, 0, 0, 0, 0, TZ_M03_M02 },
    { TZ_AMERICA_MONTSERRAT, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_NASSAU, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_NEW_YORK, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_NIPIGON, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_NOME, -540, M_NOV, 1, D_SUN, 2, 0, TZ_AKST, -480, M_MAR, 2, D_SUN, 2, 0, TZ_AKDT },
    { TZ_AMERICA_NORONHA, -120, 0, 0, 0, 0, 0, TZ_M02, -120, 0, 0, 0, 0, 0, TZ_M02 },
    { TZ_AMERICA_NORTH_DAKOTA_BEULAH, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_NORTH_DAKOTA_CENTER, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_NORTH_DAKOTA_NEW_SALEM, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_NUUK, -180, M_OCT, 5, D_SUN, -1, 0, TZ_M03_M02, -120, M_MAR, 5, D_SUN, -2, 0, TZ_M03_M02 },
    { TZ_AMERICA_OJINAGA, -420, M_NOV, 1, D_SUN, 2, 0, TZ_MST, -360, M_MAR, 2, D_SUN, 2, 0, TZ_MDT },
    { TZ_AMERICA_PANAMA, -300, 0, 0, 0, 0, 0, TZ_EST, -300, 0, 0, 0, 0, 0, TZ_EST },
    { TZ_AMERICA_PANGNIRTUNG, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_PARAMARIBO, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_PHOENIX, -420, 0, 0, 0, 0, 0, TZ_MST, -420, 0, 0, 0, 0, 0, TZ_MST },
    { TZ_AMERICA_PORTO_VELHO, -240, 0, 0, 0, 0, 0, TZ_M04, -240, 0, 0, 0, 0, 0, TZ_M04 },
    { TZ_AMERICA_PORT_AU_PRINCE, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_PORT_OF_SPAIN, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_PUERTO_RICO, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_PUNTA_ARENAS, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_RAINY_RIVER, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_RANKIN_INLET, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_RECIFE, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_REGINA, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_RESOLUTE, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_RIO_BRANCO, -300, 0, 0, 0, 0, 0, TZ_M05, -300, 0, 0, 0, 0, 0, TZ_M05 },
    { TZ_AMERICA_SANTAREM, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_AMERICA_SANTIAGO, -240, M_APR, 1, D_SUN, 0, 0, TZ_M04_M03, -180, M_SEP, 1, D_SUN, 0, 0, TZ_M04_M03 },
    { TZ_AMERICA_SANTO_DOMINGO, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_SAO_PAULO, -180, 0, 0, 0, 0, 0, TZ_M03_M02, -180, 0, 0, 0, 0, 0, TZ_M03_M02 },
    { TZ_AMERICA_SCORESBYSUND, -60, M_OCT, 5, D_SUN, 1, 0, TZ_M01_P00, 0, M_MAR, 5, D_SUN, 0, 0, TZ_M01_P00 },
    { TZ_AMERICA_SITKA, -540, M_NOV, 1, D_SUN, 2, 0, TZ_AKST, -480, M_MAR, 2, D_SUN, 2, 0, TZ_AKDT },
    { TZ_AMERICA_ST_BARTHELEMY, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_ST_JOHNS, -210, M_NOV, 1, D_SUN, 2, 0, TZ_NST, -150, M_MAR, 2, D_SUN, 2, 0, TZ_NDT },
    { TZ_AMERICA_ST_KITTS, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_ST_LUCIA, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_ST_THOMAS, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_ST_VINCENT, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_SWIFT_CURRENT, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_TEGUCIGALPA, -360, 0, 0, 0, 0, 0, TZ_CST, -360, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_AMERICA_THULE, -240, M_NOV, 1, D_SUN, 2, 0, TZ_AST, -180, M_MAR, 2, D_SUN, 2, 0, TZ_ADT },
    { TZ_AMERICA_THUNDER_BAY, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_TIJUANA, -480, M_NOV, 1, D_SUN, 2, 0, TZ_PST, -420, M_MAR, 2, D_SUN, 2, 0, TZ_PDT },
    { TZ_AMERICA_TORONTO, -300, M_NOV, 1, D_SUN, 2, 0, TZ_EST, -240, M_MAR, 2, D_SUN, 2, 0, TZ_EDT },
    { TZ_AMERICA_TORTOLA, -240, 0, 0, 0, 0, 0, TZ_AST, -240, 0, 0, 0, 0, 0, TZ_AST },
    { TZ_AMERICA_VANCOUVER, -480, M_NOV, 1, D_SUN, 2, 0, TZ_PST, -420, M_MAR, 2, D_SUN, 2, 0, TZ_PDT },
    { TZ_AMERICA_WHITEHORSE, -420, 0, 0, 0, 0, 0, TZ_MST, -420, 0, 0, 0, 0, 0, TZ_MST },
    { TZ_AMERICA_WINNIPEG, -360, M_NOV, 1, D_SUN, 2, 0, TZ_CST, -300, M_MAR, 2, D_SUN, 2, 0, TZ_CDT },
    { TZ_AMERICA_YAKUTAT, -540, M_NOV, 1, D_SUN, 2, 0, TZ_AKST, -480, M_MAR, 2, D_SUN, 2, 0, TZ_AKDT },
    { TZ_AMERICA_YELLOWKNIFE, -420, M_NOV, 1, D_SUN, 2, 0, TZ_MST, -360, M_MAR, 2, D_SUN, 2, 0, TZ_MDT },
    { TZ_ANTARCTICA_CASEY, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_ANTARCTICA_DAVIS, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ANTARCTICA_DUMONTDURVILLE, 600, 0, 0, 0, 0, 0, TZ_P10, 600, 0, 0, 0, 0, 0, TZ_P10 },
    { TZ_ANTARCTICA_MACQUARIE, 600, M_APR, 1, D_SUN, 3, 0, TZ_AEST, 660, M_OCT, 1, D_SUN, 2, 0, TZ_AEDT },
    { TZ_ANTARCTICA_MAWSON, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ANTARCTICA_MCMURDO, 720, M_APR, 1, D_SUN, 3, 0, TZ_NZST, 780, M_SEP, 5, D_SUN, 2, 0, TZ_NZDT },
    { TZ_ANTARCTICA_PALMER, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_ANTARCTICA_ROTHERA, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_ANTARCTICA_SYOWA, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_ANTARCTICA_TROLL, 0, M_OCT, 5, D_SUN, 3, 0, TZ_P00, 120, M_MAR, 5, D_SUN, 1, 0, TZ_P02 },
    { TZ_ANTARCTICA_VOSTOK, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_ARCTIC_LONGYEARBYEN, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_ASIA_ADEN, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_ASIA_ALMATY, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_ASIA_AMMAN, 120, M_OCT, 5, D_FRI, 1, 0, TZ_EET, 180, M_MAR, 5, D_THU, 24, 0, TZ_EEST },
    { TZ_ASIA_ANADYR, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_ASIA_AQTAU, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_AQTOBE, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_ASHGABAT, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_ATYRAU, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_BAGHDAD, 180, 0, 0, 0, 0, 0, TZ_P03_P04, 180, 0, 0, 0, 0, 0, TZ_P03_P04 },
    { TZ_ASIA_BAHRAIN, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_ASIA_BAKU, 240, 0, 0, 0, 0, 0, TZ_P04_P05, 240, 0, 0, 0, 0, 0, TZ_P04_P05 },
    { TZ_ASIA_BANGKOK, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_BARNAUL, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_BEIRUT, 120, M_OCT, 5, D_SUN, 0, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 0, 0, TZ_EEST },
    { TZ_ASIA_BISHKEK, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_ASIA_BRUNEI, 480, 0, 0, 0, 0, 0, TZ_P08, 480, 0, 0, 0, 0, 0, TZ_P08 },
    { TZ_ASIA_CHITA, 540, 0, 0, 0, 0, 0, TZ_P09, 540, 0, 0, 0, 0, 0, TZ_P09 },
    { TZ_ASIA_CHOIBALSAN, 480, 0, 0, 0, 0, 0, TZ_P08_P09, 480, 0, 0, 0, 0, 0, TZ_P08_P09 },
    { TZ_ASIA_COLOMBO, 330, 0, 0, 0, 0, 0, TZ_P0530, 330, 0, 0, 0, 0, 0, TZ_P0530 },
    { TZ_ASIA_DAMASCUS, 120, M_OCT, 5, D_FRI, 0, 0, TZ_EET, 180, M_MAR, 5, D_FRI, 0, 0, TZ_EEST },
    { TZ_ASIA_DHAKA, 360, 0, 0, 0, 0, 0, TZ_P06_P07, 360, 0, 0, 0, 0, 0, TZ_P06_P07 },
    { TZ_ASIA_DILI, 540, 0, 0, 0, 0, 0, TZ_P09, 540, 0, 0, 0, 0, 0, TZ_P09 },
    { TZ_ASIA_DUBAI, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_ASIA_DUSHANBE, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_FAMAGUSTA, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_ASIA_GAZA, 120, M_OCT, 4, D_SAT, 1, 0, TZ_EET, 180, M_MAR, 4, D_SAT, 0, 0, TZ_EEST },
    { TZ_ASIA_HEBRON, 120, M_OCT, 4, D_SAT, 1, 0, TZ_EET, 180, M_MAR, 4, D_SAT, 0, 0, TZ_EEST },
    { TZ_ASIA_HONG_KONG, 480, 0, 0, 0, 0, 0, TZ_HKT, 480, 0, 0, 0, 0, 0, TZ_HKT },
    { TZ_ASIA_HOVD, 420, 0, 0, 0, 0, 0, TZ_P07_P08, 420, 0, 0, 0, 0, 0, TZ_P07_P08 },
    { TZ_ASIA_HO_CHI_MINH, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_IRKUTSK, 480, 0, 0, 0, 0, 0, TZ_P08, 480, 0, 0, 0, 0, 0, TZ_P08 },
    { TZ_ASIA_ISTANBUL, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_ASIA_JAKARTA, 420, 0, 0, 0, 0, 0, TZ_WIB, 420, 0, 0, 0, 0, 0, TZ_WIB },
    { TZ_ASIA_JAYAPURA, 540, 0, 0, 0, 0, 0, TZ_WIT, 540, 0, 0, 0, 0, 0, TZ_WIT },
    { TZ_ASIA_JERUSALEM, 120, M_OCT, 5, D_SUN, 2, 0, TZ_IST, 180, M_MAR, 4, D_FRI, 2, 0, TZ_IDT },
    { TZ_ASIA_KABUL, 270, 0, 0, 0, 0, 0, TZ_P0430, 270, 0, 0, 0, 0, 0, TZ_P0430 },
    { TZ_ASIA_KAMCHATKA, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_ASIA_KARACHI, 300, 0, 0, 0, 0, 0, TZ_PKT, 300, 0, 0, 0, 0, 0, TZ_PKT },
    { TZ_ASIA_KATHMANDU, 345, 0, 0, 0, 0, 0, TZ_P0545, 345, 0, 0, 0, 0, 0, TZ_P0545 },
    { TZ_ASIA_KHANDYGA, 540, 0, 0, 0, 0, 0, TZ_P09, 540, 0, 0, 0, 0, 0, TZ_P09 },
    { TZ_ASIA_KOLKATA, 330, 0, 0, 0, 0, 0, TZ_IST, 330, 0, 0, 0, 0, 0, TZ_IST },
    { TZ_ASIA_KRASNOYARSK, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_KUALA_LUMPUR, 480, 0, 0, 0, 0, 0, TZ_P08, 480, 0, 0, 0, 0, 0, TZ_P08 },
    { TZ_ASIA_KUCHING, 480, 0, 0, 0, 0, 0, TZ_P08, 480, 0, 0, 0, 0, 0, TZ_P08 },
    { TZ_ASIA_KUWAIT, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_ASIA_MACAU, 480, 0, 0, 0, 0, 0, TZ_CST, 480, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_ASIA_MAGADAN, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_ASIA_MAKASSAR, 480, 0, 0, 0, 0, 0, TZ_WITA, 480, 0, 0, 0, 0, 0, TZ_WITA },
    { TZ_ASIA_MANILA, 480, 0, 0, 0, 0, 0, TZ_PST, 480, 0, 0, 0, 0, 0, TZ_PST },
    { TZ_ASIA_MUSCAT, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_ASIA_NICOSIA, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_ASIA_NOVOKUZNETSK, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_NOVOSIBIRSK, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_OMSK, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_ASIA_ORAL, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_PHNOM_PENH, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_PONTIANAK, 420, 0, 0, 0, 0, 0, TZ_WIB, 420, 0, 0, 0, 0, 0, TZ_WIB },
    { TZ_ASIA_PYONGYANG, 540, 0, 0, 0, 0, 0, TZ_KST, 540, 0, 0, 0, 0, 0, TZ_KST },
    { TZ_ASIA_QATAR, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_ASIA_QOSTANAY, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_ASIA_QYZYLORDA, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_RIYADH, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_ASIA_SAKHALIN, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_ASIA_SAMARKAND, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_SEOUL, 540, 0, 0, 0, 0, 0, TZ_KST, 540, 0, 0, 0, 0, 0, TZ_KST },
    { TZ_ASIA_SHANGHAI, 480, 0, 0, 0, 0, 0, TZ_CST, 480, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_ASIA_SINGAPORE, 480, 0, 0, 0, 0, 0, TZ_P08, 480, 0, 0, 0, 0, 0, TZ_P08 },
    { TZ_ASIA_SREDNEKOLYMSK, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_ASIA_TAIPEI, 480, 0, 0, 0, 0, 0, TZ_CST, 480, 0, 0, 0, 0, 0, TZ_CST },
    { TZ_ASIA_TASHKENT, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_TBILISI, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_ASIA_TEHRAN, 210, M_SEP, 0, 21, 24, 0, TZ_P0330_P0430, 270, M_MAR, 0, 21, 24, 0, TZ_P0330_P0430 },
    { TZ_ASIA_THIMPHU, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_ASIA_TOKYO, 540, 0, 0, 0, 0, 0, TZ_JST, 540, 0, 0, 0, 0, 0, TZ_JST },
    { TZ_ASIA_TOMSK, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_ULAANBAATAR, 480, 0, 0, 0, 0, 0, TZ_P08_P09, 480, 0, 0, 0, 0, 0, TZ_P08_P09 },
    { TZ_ASIA_URUMQI, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_ASIA_UST_NERA, 600, 0, 0, 0, 0, 0, TZ_P10, 600, 0, 0, 0, 0, 0, TZ_P10 },
    { TZ_ASIA_VIENTIANE, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_ASIA_VLADIVOSTOK, 600, 0, 0, 0, 0, 0, TZ_P10, 600, 0, 0, 0, 0, 0, TZ_P10 },
    { TZ_ASIA_YAKUTSK, 540, 0, 0, 0, 0, 0, TZ_P09, 540, 0, 0, 0, 0, 0, TZ_P09 },
    { TZ_ASIA_YANGON, 390, 0, 0, 0, 0, 0, TZ_P0630, 390, 0, 0, 0, 0, 0, TZ_P0630 },
    { TZ_ASIA_YEKATERINBURG, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_ASIA_YEREVAN, 240, 0, 0, 0, 0, 0, TZ_P04_P05, 240, 0, 0, 0, 0, 0, TZ_P04_P05 },
    { TZ_ATLANTIC_AZORES, -60, M_OCT, 5, D_SUN, 1, 0, TZ_M01_P00, 0, M_MAR, 5, D_SUN, 0, 0, TZ_M01_P00 },
    { TZ_ATLANTIC_BERMUDA, -240, M_NOV, 1, D_SUN, 2, 0, TZ_AST, -180, M_MAR, 2, D_SUN, 2, 0, TZ_ADT },
    { TZ_ATLANTIC_CANARY, 0, M_OCT, 5, D_SUN, 2, 0, TZ_WET, 60, M_MAR, 5, D_SUN, 1, 0, TZ_WEST },
    { TZ_ATLANTIC_CAPE_VERDE, -60, 0, 0, 0, 0, 0, TZ_M01, -60, 0, 0, 0, 0, 0, TZ_M01 },
    { TZ_ATLANTIC_FAROE, 0, M_OCT, 5, D_SUN, 2, 0, TZ_WET, 60, M_MAR, 5, D_SUN, 1, 0, TZ_WEST },
    { TZ_ATLANTIC_MADEIRA, 0, M_OCT, 5, D_SUN, 2, 0, TZ_WET, 60, M_MAR, 5, D_SUN, 1, 0, TZ_WEST },
    { TZ_ATLANTIC_REYKJAVIK, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_ATLANTIC_SOUTH_GEORGIA, -120, 0, 0, 0, 0, 0, TZ_M02, -120, 0, 0, 0, 0, 0, TZ_M02 },
    { TZ_ATLANTIC_STANLEY, -180, 0, 0, 0, 0, 0, TZ_M03, -180, 0, 0, 0, 0, 0, TZ_M03 },
    { TZ_ATLANTIC_ST_HELENA, 0, 0, 0, 0, 0, 0, TZ_GMT, 0, 0, 0, 0, 0, 0, TZ_GMT },
    { TZ_AUSTRALIA_ADELAIDE, 570, M_APR, 1, D_SUN, 3, 0, TZ_ACST, 630, M_OCT, 1, D_SUN, 2, 0, TZ_ACDT },
    { TZ_AUSTRALIA_BRISBANE, 600, 0, 0, 0, 0, 0, TZ_AEST, 600, 0, 0, 0, 0, 0, TZ_AEST },
    { TZ_AUSTRALIA_BROKEN_HILL, 570, M_APR, 1, D_SUN, 3, 0, TZ_ACST, 630, M_OCT, 1, D_SUN, 2, 0, TZ_ACDT },
    { TZ_AUSTRALIA_DARWIN, 570, 0, 0, 0, 0, 0, TZ_ACST, 570, 0, 0, 0, 0, 0, TZ_ACST },
    { TZ_AUSTRALIA_EUCLA, 525, 0, 0, 0, 0, 0, TZ_P0845_P0945, 525, 0, 0, 0, 0, 0, TZ_P0845_P0945 },
    { TZ_AUSTRALIA_HOBART, 600, M_APR, 1, D_SUN, 3, 0, TZ_AEST, 660, M_OCT, 1, D_SUN, 2, 0, TZ_AEDT },
    { TZ_AUSTRALIA_LINDEMAN, 600, 0, 0, 0, 0, 0, TZ_AEST, 600, 0, 0, 0, 0, 0, TZ_AEST },
    { TZ_AUSTRALIA_LORD_HOWE, 630, M_APR, 1, D_SUN, 2, 0, TZ_P1030_P11, 660, M_OCT, 1, D_SUN, 2, 0, TZ_P1030_P11 },
    { TZ_AUSTRALIA_MELBOURNE, 600, M_APR, 1, D_SUN, 3, 0, TZ_AEST, 660, M_OCT, 1, D_SUN, 2, 0, TZ_AEDT },
    { TZ_AUSTRALIA_PERTH, 480, 0, 0, 0, 0, 0, TZ_AWST, 480, 0, 0, 0, 0, 0, TZ_AWST },
    { TZ_AUSTRALIA_SYDNEY, 600, M_APR, 1, D_SUN, 3, 0, TZ_AEST, 660, M_OCT, 1, D_SUN, 2, 0, TZ_AEDT },
    { TZ_EUROPE_AMSTERDAM, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_ANDORRA, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_ASTRAKHAN, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_EUROPE_ATHENS, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_BELGRADE, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_BERLIN, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_BRATISLAVA, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_BRUSSELS, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_BUCHAREST, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_BUDAPEST, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_BUSINGEN, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_CHISINAU, 120, M_OCT, 5, D_SUN, 3, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 2, 0, TZ_EEST },
    { TZ_EUROPE_COPENHAGEN, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_DUBLIN, 60, M_OCT, 5, D_SUN, 2, 0, TZ_IST_GMT, 120, M_MAR, 5, D_SUN, 1, 0, TZ_IST_GMT },
    { TZ_EUROPE_GIBRALTAR, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_GUERNSEY, 0, M_OCT, 5, D_SUN, 2, 0, TZ_GMT_BST, 60, M_MAR, 5, D_SUN, 1, 0, TZ_GMT_BST },
    { TZ_EUROPE_HELSINKI, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_ISLE_OF_MAN, 0, M_OCT, 5, D_SUN, 2, 0, TZ_GMT_BST, 60, M_MAR, 5, D_SUN, 1, 0, TZ_GMT_BST },
    { TZ_EUROPE_ISTANBUL, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_EUROPE_JERSEY, 0, M_OCT, 5, D_SUN, 2, 0, TZ_GMT_BST, 60, M_MAR, 5, D_SUN, 1, 0, TZ_GMT_BST },
    { TZ_EUROPE_KALININGRAD, 120, 0, 0, 0, 0, 0, TZ_EET, 120, 0, 0, 0, 0, 0, TZ_EET },
    { TZ_EUROPE_KIEV, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_KIROV, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_EUROPE_LISBON, 0, M_OCT, 5, D_SUN, 2, 0, TZ_WET, 60, M_MAR, 5, D_SUN, 1, 0, TZ_WEST },
    { TZ_EUROPE_LJUBLJANA, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_LONDON, 0, M_OCT, 5, D_SUN, 2, 0, TZ_GMT_BST, 60, M_MAR, 5, D_SUN, 1, 0, TZ_GMT_BST },
    { TZ_EUROPE_LUXEMBOURG, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_MADRID, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_MALTA, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_MARIEHAMN, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_MINSK, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_EUROPE_MONACO, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_MOSCOW, 180, 0, 0, 0, 0, 0, TZ_MSK, 180, 0, 0, 0, 0, 0, TZ_MSK },
    { TZ_EUROPE_NICOSIA, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_OSLO, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_PARIS, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_PODGORICA, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_PRAGUE, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_RIGA, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_ROME, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_SAMARA, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_EUROPE_SAN_MARINO, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_SARAJEVO, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_SARATOV, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_EUROPE_SIMFEROPOL, 180, 0, 0, 0, 0, 0, TZ_MSK, 180, 0, 0, 0, 0, 0, TZ_MSK },
    { TZ_EUROPE_SKOPJE, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_SOFIA, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_STOCKHOLM, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_TALLINN, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_TIRANE, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_ULYANOVSK, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_EUROPE_UZHGOROD, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_VADUZ, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_VATICAN, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_VIENNA, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_VILNIUS, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_VOLGOGRAD, 180, 0, 0, 0, 0, 0, TZ_P03, 180, 0, 0, 0, 0, 0, TZ_P03 },
    { TZ_EUROPE_WARSAW, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_ZAGREB, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_EUROPE_ZAPOROZHYE, 120, M_OCT, 5, D_SUN, 4, 0, TZ_EET, 180, M_MAR, 5, D_SUN, 3, 0, TZ_EEST },
    { TZ_EUROPE_ZURICH, 60, M_OCT, 5, D_SUN, 3, 0, TZ_CET, 120, M_MAR, 5, D_SUN, 2, 0, TZ_CEST },
    { TZ_INDIAN_ANTANANARIVO, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_INDIAN_CHAGOS, 360, 0, 0, 0, 0, 0, TZ_P06, 360, 0, 0, 0, 0, 0, TZ_P06 },
    { TZ_INDIAN_CHRISTMAS, 420, 0, 0, 0, 0, 0, TZ_P07, 420, 0, 0, 0, 0, 0, TZ_P07 },
    { TZ_INDIAN_COCOS, 390, 0, 0, 0, 0, 0, TZ_P0630, 390, 0, 0, 0, 0, 0, TZ_P0630 },
    { TZ_INDIAN_COMORO, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_INDIAN_KERGUELEN, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_INDIAN_MAHE, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_INDIAN_MALDIVES, 300, 0, 0, 0, 0, 0, TZ_P05, 300, 0, 0, 0, 0, 0, TZ_P05 },
    { TZ_INDIAN_MAURITIUS, 240, 0, 0, 0, 0, 0, TZ_P04_P05, 240, 0, 0, 0, 0, 0, TZ_P04_P05 },
    { TZ_INDIAN_MAYOTTE, 180, 0, 0, 0, 0, 0, TZ_EAT, 180, 0, 0, 0, 0, 0, TZ_EAT },
    { TZ_INDIAN_REUNION, 240, 0, 0, 0, 0, 0, TZ_P04, 240, 0, 0, 0, 0, 0, TZ_P04 },
    { TZ_PACIFIC_APIA, 780, M_APR, 1, D_SUN, 4, 0, TZ_P13_P14, 840, M_SEP, 5, D_SUN, 3, 0, TZ_P13_P14 },
    { TZ_PACIFIC_AUCKLAND, 720, M_APR, 1, D_SUN, 3, 0, TZ_NZST, 780, M_SEP, 5, D_SUN, 2, 0, TZ_NZDT },
    { TZ_PACIFIC_BOUGAINVILLE, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_PACIFIC_CHATHAM, 765, M_APR, 1, D_SUN, 3, 45, TZ_P1245_P1345, 825, M_SEP, 5, D_SUN, 2, 45, TZ_P1245_P1345 },
    { TZ_PACIFIC_CHUUK, 600, 0, 0, 0, 0, 0, TZ_P10, 600, 0, 0, 0, 0, 0, TZ_P10 },
    { TZ_PACIFIC_EASTER, -360, M_APR, 1, D_SUN, -2, 0, TZ_M06_M05, -300, M_SEP, 1, D_SUN, -2, 0, TZ_M06_M05 },
    { TZ_PACIFIC_EFATE, 660, 0, 0, 0, 0, 0, TZ_P11_P12, 660, 0, 0, 0, 0, 0, TZ_P11_P12 },
    { TZ_PACIFIC_ENDERBURY, 780, 0, 0, 0, 0, 0, TZ_P13, 780, 0, 0, 0, 0, 0, TZ_P13 },
    { TZ_PACIFIC_FAKAOFO, 780, 0, 0, 0, 0, 0, TZ_P13, 780, 0, 0, 0, 0, 0, TZ_P13 },
    { TZ_PACIFIC_FIJI, 720, M_JAN, 2, D_SUN, 3, 0, TZ_P12_P13, 780, M_NOV, 2, D_SUN, 2, 0, TZ_P12_P13 },
    { TZ_PACIFIC_FUNAFUTI, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_PACIFIC_GALAPAGOS, -360, 0, 0, 0, 0, 0, TZ_M06_M05, -360, 0, 0, 0, 0, 0, TZ_M06_M05 },
    { TZ_PACIFIC_GAMBIER, -540, 0, 0, 0, 0, 0, TZ_M09, -540, 0, 0, 0, 0, 0, TZ_M09 },
    { TZ_PACIFIC_GUADALCANAL, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_PACIFIC_GUAM, 600, 0, 0, 0, 0, 0, TZ_CHST, 600, 0, 0, 0, 0, 0, TZ_CHST },
    { TZ_PACIFIC_HONOLULU, -600, 0, 0, 0, 0, 0, TZ_HST, -600, 0, 0, 0, 0, 0, TZ_HST },
    { TZ_PACIFIC_KIRITIMATI, 840, 0, 0, 0, 0, 0, TZ_P14, 840, 0, 0, 0, 0, 0, TZ_P14 },
    { TZ_PACIFIC_KOSRAE, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_PACIFIC_KWAJALEIN, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_PACIFIC_MAJURO, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_PACIFIC_MARQUESAS, -570, 0, 0, 0, 0, 0, TZ_M0930, -570, 0, 0, 0, 0, 0, TZ_M0930 },
    { TZ_PACIFIC_MIDWAY, -660, 0, 0, 0, 0, 0, TZ_SST, -660, 0, 0, 0, 0, 0, TZ_SST },
    { TZ_PACIFIC_NAURU, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_PACIFIC_NIUE, -660, 0, 0, 0, 0, 0, TZ_M11, -660, 0, 0, 0, 0, 0, TZ_M11 },
    { TZ_PACIFIC_NORFOLK, 660, M_APR, 1, D_SUN, 3, 0, TZ_P11_P12, 720, M_OCT, 1, D_SUN, 2, 0, TZ_P11_P12 },
    { TZ_PACIFIC_NOUMEA, 660, 0, 0, 0, 0, 0, TZ_P11_P12, 660, 0, 0, 0, 0, 0, TZ_P11_P12 },
    { TZ_PACIFIC_PAGO_PAGO, -660, 0, 0, 0, 0, 0, TZ_SST, -660, 0, 0, 0, 0, 0, TZ_SST },
    { TZ_PACIFIC_PALAU, 540, 0, 0, 0, 0, 0, TZ_P09, 540, 0, 0, 0, 0, 0, TZ_P09 },
    { TZ_PACIFIC_PITCAIRN, -480, 0, 0, 0, 0, 0, TZ_M08, -480, 0, 0, 0, 0, 0, TZ_M08 },
    { TZ_PACIFIC_POHNPEI, 660, 0, 0, 0, 0, 0, TZ_P11, 660, 0, 0, 0, 0, 0, TZ_P11 },
    { TZ_PACIFIC_PORT_MORESBY, 600, 0, 0, 0, 0, 0, TZ_P10, 600, 0, 0, 0, 0, 0, TZ_P10 },
    { TZ_PACIFIC_RAROTONGA, -600, 0, 0, 0, 0, 0, TZ_M10_M0930, -600, 0, 0, 0, 0, 0, TZ_M10_M0930 },
    { TZ_PACIFIC_SAIPAN, 600, 0, 0, 0, 0, 0, TZ_CHST, 600, 0, 0, 0, 0, 0, TZ_CHST },
    { TZ_PACIFIC_TAHITI, -600, 0, 0, 0, 0, 0, TZ_M10, -600, 0, 0, 0, 0, 0, TZ_M10 },
    { TZ_PACIFIC_TARAWA, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_PACIFIC_TONGATAPU, 780, 0, 0, 0, 0, 0, TZ_P13_P14, 780, 0, 0, 0, 0, 0, TZ_P13_P14 },
    { TZ_PACIFIC_WAKE, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
    { TZ_PACIFIC_WALLIS, 720, 0, 0, 0, 0, 0, TZ_P12, 720, 0, 0, 0, 0, 0, TZ_P12 },
};

#endif /* TZDATA_H */
